<?php
/**
 * Created by PhpStorm.
 * User: zhangjun
 * Date: 2017/6/23
 * Time: 9:27
 */

namespace frontend\widgets;

use backend\models\GoodsCategory;
use yii\base\Widget;

class CategoryWidget extends  Widget{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function run()
    {
        //检测redis是否有商品分类缓存
//        $redis=new \Redis();//实例化redis对象
//        $redis->connect('127.0.0.1');//连接redis
//        $category_html=$redis->get('category_html');//获取首页分类缓存
//
//        if (!$category_html){//,没有就创建
            //获取分类数据
            $goodsCategories=GoodsCategory::findAll(['parent_id'=>0]);

            //将数据输送到用来缓存的页面
            $category_html=$this->renderFile('@app/widgets/views/category.php',['goodsCategories'=>$goodsCategories]);
            //缓存到redis中
//            $redis->set('category_html',$category_html);
//        }

        //有就直接调用返回
        return $category_html;
    }
}